name: Päivitä data
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install shapely
      - run: python fetch_data.py
      - name: Tallenna uusi data repoon
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add postal_yields.geojson
          git commit -m "Päivitä postal_yields.geojson" || echo "Ei muutoksia"
          git push
